### ISSUE TITLE
App doesn't start if EOHD path set wrong

### ISSUE THREAD

**Issue by Vixoros** [Coolsonickirby/EO_Mod_Manager#1]
With EOHD path incorrectly set to `C:\Program Files (x86)\Steam\steamapps\common\EOHD\Etrian Odyssey_Data\`, application crashes silently. Console log shows the following error:

```
Unhandled exception. System.Windows.Markup.XamlParseException: 'The invocation of the constructor on type 'EO_Mod_Manager.MainWindow' that matches the specified binding constraints threw an exception.' Line number '6' and line position '9'.
 ---> System.IO.FileNotFoundException: Could not find file 'C:\Program Files (x86)\Steam\steamapps\common\EOHD\Etrian Odyssey_Data\GameAssembly.dll'.
File name: 'C:\Program Files (x86)\Steam\steamapps\common\EOHD\Etrian Odyssey_Data\GameAssembly.dll'
   at System.IO.FileInfo.get_Length()
   at EO_Mod_Manager.MainWindow.SetupGames() in C:\Users\maxgo\Source\Repos\EO_Mod_Managerthemes\MainWindow.xaml.cs:line 86
   at EO_Mod_Manager.MainWindow..ctor() in C:\Users\maxgo\Source\Repos\EO_Mod_Managerthemes\MainWindow.xaml.cs:line 72
   --- End of inner exception stack trace ---
```

The only way to fix is to delete/modify the user.config at `C:\Users\<user>\AppData\Local\EO_Mod_Manager`

App should fall back to initial configuration screen if the paths are wrong

**Comment by Coolsonickirby** [comment]
Fixed with the [latest commit](https://github.com/Coolsonickirby/EO_Mod_Manager/commit/72469f5d383f81ab966b021a50c8d690e28661ed). Thank you very much for bringing it to our attention!
