### ISSUE TITLE
No confirmation button is being shown

### ISSUE THREAD

**Issue by Kesler031** [Coolsonickirby/EO_Mod_Manager#2]
How am I supposed to install any mods? It looks like the windows is cut off, and I cant resize to find any buttons.
![Captura de Tela (35)](https://github.com/Coolsonickirby/EO_Mod_Manager/assets/137836769/c45e8078-14e1-44dd-9b3c-c432be0254ef)
![Captura de Tela (36)](https://github.com/Coolsonickirby/EO_Mod_Manager/assets/137836769/6b06add1-e676-4997-bccb-3ad9f0e9df59)

**Comment by MadMax1960** [comment]
Fixed with latest update.
